### ISSUE TITLE
Invalid layout on iOS 10

### ISSUE THREAD

**Issue by iomark** [onmyway133/Dropdowns#8]
There is an invalid layout on iPhone 7 simulator with iOS 10.3 (Xcode 9.1)

<img src="https://user-images.githubusercontent.com/1295212/33374353-7ca543e6-d50e-11e7-92f7-9dcd3f03073a.png" height="480">

**Comment by sethsandaru** [comment]
My simulator is fine but my device (5s + iPad mini 1) got this too.

**Comment by AbhijeetMallick** [comment]
@iomark Getting the same issue for iOS 10. Are you able to fix it?

**Comment by alissonbarauna** [comment]
Did you guys find a workaround for that?
I would be grateful for any help.
Thanks.

**Comment by alissonbarauna** [comment]
Hi @AbhijeetMallick ! It worked ike a charm! Thank you sooo much.
